// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDExyJJ8Mt3RmvLah4Y8l_e5wIGjhs0Atw',
    appId: '1:405730688715:web:6df13765147a58db82a54e',
    messagingSenderId: '405730688715',
    projectId: 'pipheaksa',
    authDomain: 'pipheaksa.firebaseapp.com',
    storageBucket: 'pipheaksa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgxD81Xbbcio0XO-80bSsNTLSapD9a-aQ',
    appId: '1:405730688715:android:4a10d21cab63b99882a54e',
    messagingSenderId: '405730688715',
    projectId: 'pipheaksa',
    storageBucket: 'pipheaksa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS3kueRZ8FoW9hOmMQMAUJ89mesulPBJc',
    appId: '1:405730688715:ios:740b676aa69270da82a54e',
    messagingSenderId: '405730688715',
    projectId: 'pipheaksa',
    storageBucket: 'pipheaksa.appspot.com',
    iosClientId: '405730688715-sp6nf4qakagafik1bvv78qmfmspln120.apps.googleusercontent.com',
    iosBundleId: 'com.example.pipheaksa',
  );
}
